ComidaRapida/Controllers/PedidosController.cs
using ComidaRapida.Models;
using ComidaRapida.Repositorios;
using Microsoft.AspNetCore.Mvc;

namespace ComidaRapida.Controllers
{
    public class PedidosController : Controller
    {
        private readonly IRepositorioPedidos repositorioPedidos;

        public PedidosController(IRepositorioPedidos repositorioPedidos)
        {
            this.repositorioPedidos = repositorioPedidos;
        }

        [HttpGet]
        public async Task<IActionResult> Listar()
        {
            var pedidos = await repositorioPedidos.Listar();
            return View(pedidos);
        }

        [HttpGet]
        public IActionResult Crear()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Crear(PedidoViewModel pedido)
        {
            //Valida los campos del modelo
            if (!ModelState.IsValid)
            {
                return View(pedido);
            }

            await repositorioPedidos.Crear(pedido);

            return RedirectToAction("Listar");
        }

        [HttpGet]
        public async Task<IActionResult> Editar(int IdPedido)
        {
            var pedido = await repositorioPedidos.ObtenerId(IdPedido);

            if (pedido is null)
            {
                return RedirectToAction("NoEncontrado", "Home");
            }

            return View(pedido);

        }

        [HttpPost]
        public async Task<IActionResult> Editar(PedidoViewModel pedido)
        {
            var pedidoExiste = await repositorioPedidos.ObtenerId(pedido.IdPedido);

            if (pedidoExiste is null)
            {
                return RedirectToAction("NoEncontrado", "Home");
            }

            await repositorioPedidos.Actualizar(pedido);

            return RedirectToAction("Listar");
        }

        [HttpGet]
        public async Task<IActionResult> Eliminar(int IdPedido)
        {
            var pedido = await repositorioPedidos.ObtenerId(IdPedido);

            if (pedido is null)
            {
                return RedirectToAction("NoEncontrado", "Home");
            }

            return View(pedido);
        }

        [HttpPost]
        public async Task<IActionResult> Eliminar(PedidoViewModel pedido)
        {
            await repositorioPedidos.Eliminar(pedido.IdPedido);
            return RedirectToAction("Listar");
        }

        [HttpGet]
        public async Task<IActionResult> Entregar(int IdPedido)
        {
            var pedido = await repositorioPedidos.ObtenerId(IdPedido);

            if (pedido is null)
            {
                return RedirectToAction("NoEncontrado", "Home");
            }

            return View(pedido);

        }

        [HttpPost]
        public async Task<IActionResult> Entregar(PedidoViewModel pedido)
        {
            var pedidoExiste = await repositorioPedidos.ObtenerId(pedido.IdPedido);

            if (pedidoExiste is null)
            {
                return RedirectToAction("NoEncontrado", "Home");
            }

            await repositorioPedidos.Entregar(pedido);

            return RedirectToAction("Listar");
        }
    }
}

ComidaRapida/Controllers/RepartidoresController.cs
using ComidaRapida.Models;
using ComidaRapida.Repositorios;
using Microsoft.AspNetCore.Mvc;

namespace ComidaRapida.Controllers
{
    public class RepartidoresController : Controller
    {
        private readonly IRepositorioRepartidores repositorioRepartidores;

        public RepartidoresController(IRepositorioRepartidores repositorioRepartidores)
        {
            this.repositorioRepartidores = repositorioRepartidores;
        }

        [HttpGet]
        public async Task<IActionResult> Listar()
        {
            var repartidores = await repositorioRepartidores.Listar();
            return View(repartidores);
        }

        [HttpGet]
        public async Task<IActionResult> VerificarExisteVendedor(string nombre, string usuario)
        {
            var existeRepartidor = await repositorioRepartidores.Existe(nombre, usuario);

            if (existeRepartidor)
            {
                return Json($"El repartidor ya existe");
            }

            return Json(true);
        }

        [HttpGet]
        public IActionResult Crear()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Crear(UsuarioViewModel repartidor)
        {
            //Valida los campos del modelo
            if (!ModelState.IsValid)
            {
                return View(repartidor);
            }

            //Valida si ya existe el apoyo a insertar
            var existeVendedor = await repositorioRepartidores.Existe(repartidor.Nombre, repartidor.Usuario);

            if (existeVendedor)
            {
                ModelState.AddModelError(nameof(repartidor.Nombre), $"El vendedor ya se encuentra registrado");

                return View(repartidor);
            }

            await repositorioRepartidores.Crear(repartidor);

            return RedirectToAction("Listar");
        }

        [HttpGet]
        public async Task<IActionResult> Editar(int IdUsuario)
        {
            var repartidor = await repositorioRepartidores.ObtenerId(IdUsuario);

            if (repartidor is null)
            {
                return RedirectToAction("NoEncontrado", "Home");
            }

            return View(repartidor);

        }

        [HttpPost]
        public async Task<IActionResult> Editar(UsuarioViewModel repartidor)
        {
            var vendedorExiste = await repositorioRepartidores.ObtenerId(repartidor.IdUsuario);

            if (vendedorExiste is null)
            {
                return RedirectToAction("NoEncontrado", "Home");
            }

            await repositorioRepartidores.Actualizar(repartidor);

            return RedirectToAction("Listar");
        }

        [HttpGet]
        public async Task<IActionResult> Eliminar(int IdUsuario)
        {
            var repartidor = await repositorioRepartidores.ObtenerId(IdUsuario);

            if (repartidor is null)
            {
                return RedirectToAction("NoEncontrado", "Home");
            }

            return View(repartidor);
        }

        [HttpPost]
        public async Task<IActionResult> Eliminar(UsuarioViewModel repartidor)
        {
            await repositorioRepartidores.Eliminar(repartidor.IdUsuario);
            return RedirectToAction("Listar");
        }
    }
}

ComidaRapida/Controllers/VendedoresController.cs
using ComidaRapida.Models;
using ComidaRapida.Repositorios;
using Microsoft.AspNetCore.Mvc;

namespace ComidaRapida.Controllers
{
    public class VendedoresController : Controller
    {
        private readonly IRepositorioVendedores repositorioVendedores;

        public VendedoresController(IRepositorioVendedores repositorioVendedores)
        {
            this.repositorioVendedores = repositorioVendedores;
        }

        [HttpGet]
        public async Task<IActionResult> Listar()
        {
            var vendedores = await repositorioVendedores.Listar();
            return View(vendedores);
        }

        [HttpGet]
        public async Task<IActionResult> VerificarExisteVendedor(string nombre, string usuario)
        {
            var existeVendedor = await repositorioVendedores.Existe(nombre, usuario);

            if (existeVendedor)
            {
                return Json($"El vendedor ya existe");
            }

            return Json(true);
        }

        [HttpGet]
        public IActionResult Crear()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Crear(UsuarioViewModel vendedor)
        {
            //Valida los campos del modelo
            if (!ModelState.IsValid)
            {
                return View(vendedor);
            }

            //Valida si ya existe el apoyo a insertar
            var existeVendedor = await repositorioVendedores.Existe(vendedor.Nombre, vendedor.Usuario);

            if (existeVendedor)
            {
                ModelState.AddModelError(nameof(vendedor.Nombre), $"El vendedor ya se encuentra registrado");

                return View(vendedor);
            }

            await repositorioVendedores.Crear(vendedor);

            return RedirectToAction("Listar");
        }

        [HttpGet]
        public async Task<IActionResult> Editar(int IdUsuario)
        {
            var vendedor = await repositorioVendedores.ObtenerId(IdUsuario);

            if (vendedor is null)
            {
                return RedirectToAction("NoEncontrado", "Home");
            }

            return View(vendedor);

        }

        [HttpPost]
        public async Task<IActionResult> Editar(UsuarioViewModel vendedor)
        {
            var vendedorExiste = await repositorioVendedores.ObtenerId(vendedor.IdUsuario);

            if (vendedorExiste is null)
            {
                return RedirectToAction("NoEncontrado", "Home");
            }

            await repositorioVendedores.Actualizar(vendedor);

            return RedirectToAction("Listar");
        }

        [HttpGet]
        public async Task<IActionResult> Eliminar(int IdUsuario)
        {
            var vendedor = await repositorioVendedores.ObtenerId(IdUsuario);

            if (vendedor is null)
            {
                return RedirectToAction("NoEncontrado", "Home");
            }

            return View(vendedor);
        }

        [HttpPost]
        public async Task<IActionResult> Eliminar(UsuarioViewModel vendedor)
        {
            await repositorioVendedores.Eliminar(vendedor.IdUsuario);
            return RedirectToAction("Listar");
        }


    }
}

ComidaRapida/Views/Shared/_Footer.cshtml
<footer class="main-footer">
    <!-- Default to the left -->
    <strong>Comida Rápida &copy; 2022</strong>
    <!-- To the right -->
    <div class="float-right d-none d-sm-inline">
        TEC de Tezitlán
    </div>

</footer>

ComidaRapida/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ComidaRapida</title>
    <!-- Google Font: Source Sans Pro -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback">
    <!-- BootstrapIcons -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.8.1/font/bootstrap-icons.css" asp-append-version="true">
    <!-- DataTables -->
    <link rel="stylesheet" href="../../plugins/datatables-bs4/css/dataTables.bootstrap4.min.css">
    <link rel="stylesheet" href="../../plugins/datatables-responsive/css/responsive.bootstrap4.min.css">
    <link rel="stylesheet" href="../../plugins/datatables-buttons/css/buttons.bootstrap4.min.css">
    <!-- Theme style -->
    <link rel="stylesheet" href="../../dist/css/adminlte.min.css">
</head>
<body class="hold-transition layout-top-nav">

    <div class="wrapper">

        <partial name="_Navbar" />

        @RenderBody()

        <partial name="_Footer" />
    </div>


    <!-- jQuery -->
    <script src="../../plugins/jquery/jquery.min.js"></script>
    <!-- Bootstrap 4 -->
    <script src="../../plugins/bootstrap/js/bootstrap.bundle.min.js"></script>
    <!-- AdminLTE App -->
    <script src="../../dist/js/adminlte.min.js"></script>
    <!-- DataTables  & Plugins -->
    <script src="../../plugins/datatables/jquery.dataTables.min.js"></script>
    <script src="../../plugins/datatables-bs4/js/dataTables.bootstrap4.min.js"></script>
    <script src="../../plugins/datatables-responsive/js/dataTables.responsive.min.js"></script>
    <script src="../../plugins/datatables-responsive/js/responsive.bootstrap4.min.js"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

ComidaRapida/Views/Shared/_Navbar.cshtml
<nav class="main-header navbar navbar-expand-md navbar-light navbar-white">
    <div class="container-fluid">
        <a href="../../index3.html" class="navbar-brand">
            <span class="brand-text font-weight-light">Comida Rápida</span>
        </a>

        <div class="collapse navbar-collapse order-3" id="navbarCollapse">
            <!-- Left navbar links -->
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a href="#" class="nav-link">Inicio</a>
                </li>
                <li class="nav-item">
                    <a asp-controller="Pedidos" asp-action="Listar" class="nav-link">Pedidos</a>
                </li>
                <li class="nav-item">
                    <a asp-controller="Vendedores" asp-action="Listar" class="nav-link">Vendedores</a>
                </li>
                <li class="nav-item">
                    <a asp-controller="Repartidores" asp-action="Listar" class="nav-link">Repartidores</a>
                </li>
                <li class="nav-item">
                    <a asp-controller="Repartidores" asp-action="Listar" class="nav-link">Pedidos Recibidos</a>
                </li>
                <li class="nav-item">
                    <a asp-controller="Repartidores" asp-action="Listar" class="nav-link">Pedidos Entregados</a>
                </li>


            </ul>

         
        </div>

    </div>
</nav>